export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";
export const PATCH_COMMENT_SUCCESS = "PATCH_COMMENT_SUCCESS";
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const COMMENT_FAILURE = "COMMENT_FAILURE";
export const COMMENT_REQUEST = "COMMENT_REQUEST";


