export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS";
export const GET_BLOG_SUCCESS = "GET_BLOG_SUCCESS";
export const GET_USER_BLOG_SUCCESS = "GET_USER_BLOG_SUCCESS";
export const GET_SINGLE_BLOG_SUCCESS = "GET_SINGLE_BLOG_SUCCESS";
export const PATCH_BLOG_SUCCESS = "PATCH_BLOG_SUCCESS";
export const POST_BLOG_SUCCESS = "POST_BLOG_SUCCESS";
export const BLOG_FAILURE = "BLOG_FAILURE";
export const BLOG_REQUEST = "BLOG_REQUEST";
export const BLOG_TOTAL_SUCCESS = "BLOG_TOTAL_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const SIGNUP_LOADING = "SIGNUP_LOADING";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

